import { Geist, Geist_Mono } from "next/font/google";
import styles from "./page.module.css";
import "./page.module.css";
import { Header } from "./components/header/header.js"
import { Footer } from "./components/footer/footer.js"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <div className={styles.content}>
          <Header/>
        {children}
        <div className={styles.item3}>
        <Footer/>
        </div>
        </div>
      </body>
    </html>
  );
}
